Round6/force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <description>Usado para representar o jogo da série &quot;Round 6&quot;</description>
    <label>Round</label>
    <nameField>
        <displayFormat>Round-{00000}</displayFormat>
        <label>Número do Round</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Round6/force-app/main/default/objects/Round__c/fields/InicioJogos__c.field-meta.xml
<CustomField>
    <fullName>InicioJogos__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Data de início dos jogos.</description>
    <inlineHelpText>Data de início dos jogos.</inlineHelpText>
    <label>Início dos Jogos</label>
    <type>Date</type>
</CustomField>

Round6/force-app/main/default/objects/Round__c/fields/TerminoJogos__c.field-meta.xml
<CustomField>
    <fullName>TerminoJogos__c</fullName>
    <description>Data de término dos jogos.</description>
    <inlineHelpText>Data de término dos jogos.</inlineHelpText>
    <label>Término dos Jogos</label>
    <type>Date</type>
</CustomField>

Round6/force-app/main/default/classes/UpdateFieldsBatchable.cls
public with sharing class UpdateFieldsBatchable implements Database.Batchable<sObject>, Database.Stateful {
    
    String query = 'SELECT Id, Name, TerminoJogos__c, InicioJogos__c FROM Round__c WHERE Id in :id';
    Map<SObjectField, Object> mapa;

    public UpdateFieldsBatchable(String query, Map<SObjectField, Object> mapa) {
        this.query = query;
        this.mapa = mapa;
    }

    public Database.QueryLocator start(Database.BatchaBleContext BC) {
        System.debug('Metodo Database.QueryLocator');
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<SObject> scope) {
        System.debug('Metodo execute');
        System.debug('SCOPE: ' + JSON.serialize(scope));

        for (SObject record : scope) {
            //JSON.serialize(record.getPopulatedFieldsAsMap());
            for (Schema.SOBjectField key : mapa.keySet()) {
                record.put(key, mapa.get(key));
            }
        }

        //update scope;

    }

    public void finish(Database.BatchableContext BC) {
        System.debug('Metodo finish');
        //sendLog();
    }

    
}