Round6/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Round6/force-app/main/default/objects/Jogador__c/fields/DataMorte__c.field-meta.xml
<CustomField>
    <fullName>DataMorte__c</fullName>
    <description>Usado para a data da morte</description>
    <inlineHelpText>Data da morte do jogador</inlineHelpText>
    <label>Data da Morte</label>
    <type>DateTime</type>
</CustomField>

Round6/force-app/main/default/objects/Jogador__c/fields/Morreu__c.field-meta.xml
<CustomField>
    <fullName>Morreu__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo que conreola se morreu</description>
    <inlineHelpText>Campo que conreola se morreu</inlineHelpText>
    <label>Morreu</label>
    <type>Checkbox</type>
</CustomField>

Round6/force-app/main/default/classes/JogadorHelper.cls
public class JogadorHelper {

    public static void elimiarJogador(Jogador__c jogadorEliminado){

        //TODO so marcar o morreu pq vai entrar na trigger after e before de jogador (ver codigo do Arthur)
        jogadorEliminado.Eliminado__c = true;
        jogadorEliminado.Morreu__c = true;
        jogadorEliminado.DataMorte__c = System.now();
    
        System.debug('elimiarJogador: ' + JSON.serialize(jogadorEliminado));
        update jogadorEliminado;
    }

}