Round6/force-app/main/default/objects/Jogador__c/Jogador__c.object-meta.xml
<CustomObject>
    <description>Participante do jogo</description>
    <label>Jogador</label>
    <nameField>
        <displayFormat>Jogador-{000}</displayFormat>
        <label>Número do Jogador</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jogadores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Round6/force-app/main/default/objects/ParticipantesPartida__c/ParticipantesPartida__c.object-meta.xml
<CustomObject>
    <description>Tabela de ligação entre Jogadores e partida</description>
    <label>Participante da Partida</label>
    <nameField>
        <displayFormat>Par-{000000}</displayFormat>
        <label>Número do Participante da Partida</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participantes da Partida</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Round6/force-app/main/default/objects/ParticipantesPartida__c/fields/Jogador__c.field-meta.xml
<CustomField>
    <fullName>Jogador__c</fullName>
    <description>Jogador da partida</description>
    <inlineHelpText>Jogador da partida</inlineHelpText>
    <label>Jogador</label>
    <referenceTo>Jogador__c</referenceTo>
    <relationshipLabel>Participantes da Partida</relationshipLabel>
    <relationshipName>ParticipantesPartida</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Round6/force-app/main/default/objects/Partida__c/Partida__c.object-meta.xml
<CustomObject>
    <description>Jogo de cada round</description>
    <label>Partida</label>
    <nameField>
        <label>Nome de Partida</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partidas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Round6/force-app/main/default/objects/Partida__c/fields/TerminoPartida__c.field-meta.xml
<CustomField>
    <fullName>TerminoPartida__c</fullName>
    <description>Data e hora de término da partida.</description>
    <inlineHelpText>Data e hora de término da partida.</inlineHelpText>
    <label>Término da Partida</label>
    <type>DateTime</type>
</CustomField>

Round6/force-app/main/default/classes/BatatinhaFrita.cls
public class BatatinhaFrita implements IPartida {
    public void execute(Id idPartida)
    {
        ParticipantesPartida__c[] participantes = [SELECT Jogador__c FROM ParticipantesPartida__c WHERE Partida__c = :idPartida];
        System.debug(participantes);
        Jogador__c[] jogadores = new List<Jogador__c>();
        
        Integer mortes = (Integer) participantes.size() / 2;
        
        for(Integer i = 0; i < mortes; i++)
        {
            Jogador__c jogador = new Jogador__c();
            jogador.Id = participantes[i].Jogador__c;
            jogador.Eliminado__c = true;
            jogadores.add(jogador);
        }
        
        update jogadores;
        
        Partida__c partida = new Partida__c(Id = idPartida, TerminoPartida__c = System.now());
        //update new Partida__c(Id = idPartida, TerminoPartida__c = System.now());
        
        update partida;
    }
}