Round6/force-app/main/default/objects/Candidato__c/Candidato__c.object-meta.xml
<CustomObject>
    <description>Um candidato é uma pessoa que foi convidada a particidar dos jogos mas ainda não aceitou.</description>
    <label>Candidato</label>
    <nameField>
        <label>Nome dd Candidato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidatos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Round6/force-app/main/default/objects/Candidato__c/fields/Celular__c.field-meta.xml
<CustomField>
    <fullName>Celular__c</fullName>
    <description>Usado para meio de contato</description>
    <inlineHelpText>Usado para meio de contato</inlineHelpText>
    <label>Celular</label>
    <type>Phone</type>
</CustomField>

Round6/force-app/main/default/objects/Candidato__c/fields/CEPAlterado__c.field-meta.xml
<CustomField>
    <fullName>CEPAlterado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CEP alterado</label>
    <type>Checkbox</type>
</CustomField>

Round6/force-app/main/default/objects/Candidato__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Usado para meio de contato</description>
    <inlineHelpText>Usado para meio de contato</inlineHelpText>
    <label>Email</label>
    <type>Email</type>
</CustomField>

Round6/force-app/main/default/objects/Round__c/Round__c.object-meta.xml
<CustomObject>
    <description>Usado para representar o jogo da série &quot;Round 6&quot;</description>
    <label>Round</label>
    <nameField>
        <displayFormat>Round-{00000}</displayFormat>
        <label>Número do Round</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rounds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Round6/force-app/main/default/objects/Round__c/fields/InicioJogos__c.field-meta.xml
<CustomField>
    <fullName>InicioJogos__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <description>Data de início dos jogos.</description>
    <inlineHelpText>Data de início dos jogos.</inlineHelpText>
    <label>Início dos Jogos</label>
    <type>Date</type>
</CustomField>

Round6/force-app/main/default/objects/Round__c/fields/TerminoJogos__c.field-meta.xml
<CustomField>
    <fullName>TerminoJogos__c</fullName>
    <description>Data de término dos jogos.</description>
    <inlineHelpText>Data de término dos jogos.</inlineHelpText>
    <label>Término dos Jogos</label>
    <type>Date</type>
</CustomField>

Round6/force-app/main/default/classes/UpdateFieldsBatchableMain.cls
public with sharing class UpdateFieldsBatchableMain {

    public UpdateFieldsBatchableMain() {

        /*Map<Schema.SObjectField, Object> fieldsValuesMap1 = new Map<Schema.SObjectField, Object> {
            Account.Name => 'Name',
            Account.BillingState => 'RJ'
        };*/

        /*Map<Schema.SObjectField, Object> fieldsValuesMap2 = new Map<Schema.SObjectField, Object> {
            Candidato__c.CEPAlterado__c => false,
            Candidato__c.Email__c => 'ma@oie.com'
        };*/

        Map<Schema.SObjectField, Object> fieldsValuesMap = new Map<Schema.SObjectField, Object> {
            Round__c.Name => 'Round-00001',
            Round__c.TerminoJogos__c => Datetime.now().date(),
            Round__c.InicioJogos__c => Datetime.now().date()
        };

        Set<Id> id = new Set<Id>{'a045f000003YVlEAAW'};

        //String query = 'SELECT Aceite__c, Bairro__c, Celular__c, CEPAlterado__c FROM Candidato__c';
        String query = 'SELECT Id, Name, TerminoJogos__c, InicioJogos__c FROM Round__c WHERE Id in :id';


        Database.executeBatch(new UpdateFieldsBatchable(query, fieldsValuesMap), 1);

        /*for (Schema.SObjectField field : fieldsValuesMap1.keySet()) {
            System.debug('FIELD: ' +  field);
        }

        for (Object value : fieldsValuesMap1.values()) {
            System.debug('VALORES: ' + value);
        }*/
    }
}