Round6/force-app/main/default/objects/Candidato__c/Candidato__c.object-meta.xml
<CustomObject>
    <description>Um candidato é uma pessoa que foi convidada a particidar dos jogos mas ainda não aceitou.</description>
    <label>Candidato</label>
    <nameField>
        <label>Nome dd Candidato</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Candidatos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Round6/force-app/main/default/objects/Candidato__c/fields/CEPAlterado__c.field-meta.xml
<CustomField>
    <fullName>CEPAlterado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>CEP alterado</label>
    <type>Checkbox</type>
</CustomField>

Round6/force-app/main/default/classes/CandidatosCEPAlteradoBatchable.cls
public without sharing class CandidatosCEPAlteradoBatchable implements Database.Batchable<sObject>, Database.Stateful {
    
    String error;

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(CandidatosSelector.getQueryLocatorCEPBatchable());
    }
  
    //TODO: atualizar o campo CEPAlterado__c para FALSE
    public void execute(Database.BatchableContext BC, List<Candidato__c> scope) {
        for (Candidato__c record : scope) {
            record.CEPAlterado__c = false;
            error += record.Id + ' - ';
        }
    }
  
    public void finish(Database.BatchableContext BC) {
        System.debug('error: ' + error);
    }
}